# Data Cleaning

In [1]:
import pandas as pd
import numpy as np
import joblib 
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('G:\\Ethans\\ML\\Projects\\Final Projects\\Airline_ML\\Data\\Airline1.csv')

In [3]:
df

,ID,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,1,IndiGo,24-03-2019,Banglore,New Delhi,BLR _ DEL,22:20,22-03-2019 01:10,2h 50m,non-stop,No info,3897.0
1,2,Air India,01-05-2019,Kolkata,Banglore,CCU _ IXR _ BBI _ BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,3,Jet Airways,09-06-2019,Delhi,Cochin,DEL _ LKO _ BOM _ COK,09:25,10-06-2019 04:25,19h,2 stops,No info,13882.0
3,4,IndiGo,12-05-2019,Kolkata,Banglore,CCU _ NAG _ BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,5,IndiGo,01-03-2019,Banglore,New Delhi,BLR _ NAG _ DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10684,10679,Air Asia,09-04-2019,Kolkata,Banglore,CCU ? BLR,19:55,22:25,2h 30m,non-stop,No info,4107.0
10685,10680,Air India,27-04-2019,Kolkata,Banglore,CCU ? BLR,20:45,23:20,2h 35m,non-stop,No info,4145.0
10686,10681,Jet Airways,27-04-2019,Banglore,Delhi,BLR ? DEL,08:20,11:20,3h,non-stop,No info,7229.0
10687,10682,Vistara,01-03-2019,Banglore,New Delhi,BLR ? DEL,11:30,14:10,2h 40m,non-stop,No info,12648.0
10688,10683,Air India,09-05-2019,Delhi,Cochin,DEL ? GOI ? BOM ? COK,10:55,19:15,8h 20m,2 stops,No info,11753.0

## Handling Null Values

In [4]:
df.isnull().sum()

ID                 0
Airline            0
Date_of_Journey    0
Source             2
Destination        2
Route              3
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              3
dtype: int64

In [5]:
df[df['Source'].isnull()]
df.fillna({'Source': df['Source'].mode()[0]}, inplace=True)

In [6]:
df[df['Destination'].isnull()]
df.fillna({'Destination': df['Destination'].mode()[0]}, inplace=True)

In [7]:
df[df['Route'].isnull()]
df.fillna({'Route': df['Route'].mode()[0]}, inplace=True)

In [8]:
df[df['Price'].isnull()]
df.fillna({'Price': df['Price'].mean()}, inplace=True)

In [9]:
df['Total_Stops'].isnull().sum()
df.fillna({'Total_Stops': df['Total_Stops'].mode()[0]}, inplace=True)

In [10]:
df.isnull().sum()

ID                 0
Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

## Handling Spelling Mistakes

In [11]:
df['Destination'].value_counts()

Destination
Cochin       4539
Banglore     2873
Delhi        1267
New Delhi     932
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [12]:
df['Destination'].replace({'New Delhi': 'Delhi'}, inplace=True)
df['Destination'].value_counts()

C:\Users\bhato\AppData\Local\Temp\ipykernel_21092\2725584720.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Destination'].replace({'New Delhi': 'Delhi'}, inplace=True)

Destination
Cochin       4539
Banglore     2873
Delhi        2199
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [13]:
df.columns

Index(['ID', 'Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [14]:
df

,ID,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,1,IndiGo,24-03-2019,Banglore,Delhi,BLR _ DEL,22:20,22-03-2019 01:10,2h 50m,non-stop,No info,3897.0
1,2,Air India,01-05-2019,Kolkata,Banglore,CCU _ IXR _ BBI _ BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,3,Jet Airways,09-06-2019,Delhi,Cochin,DEL _ LKO _ BOM _ COK,09:25,10-06-2019 04:25,19h,2 stops,No info,13882.0
3,4,IndiGo,12-05-2019,Kolkata,Banglore,CCU _ NAG _ BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,5,IndiGo,01-03-2019,Banglore,Delhi,BLR _ NAG _ DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10684,10679,Air Asia,09-04-2019,Kolkata,Banglore,CCU ? BLR,19:55,22:25,2h 30m,non-stop,No info,4107.0
10685,10680,Air India,27-04-2019,Kolkata,Banglore,CCU ? BLR,20:45,23:20,2h 35m,non-stop,No info,4145.0
10686,10681,Jet Airways,27-04-2019,Banglore,Delhi,BLR ? DEL,08:20,11:20,3h,non-stop,No info,7229.0
10687,10682,Vistara,01-03-2019,Banglore,Delhi,BLR ? DEL,11:30,14:10,2h 40m,non-stop,No info,12648.0
10688,10683,Air India,09-05-2019,Delhi,Cochin,DEL ? GOI ? BOM ? COK,10:55,19:15,8h 20m,2 stops,No info,11753.0

## Removing Irrelevant Columns

In [4]:
# Dropping the columns which are not required for the analysis
#ID: Unique identifier for each flight, not useful for prediction.
#Additional_Info: Contains information about the flight, but not useful for prediction.
#Route: Contains the route of the flight, but not useful for prediction.
df.drop(['ID','Additional_Info','Route'], axis=1, inplace=True)

NameError: name 'df' is not defined

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10689 entries, 0 to 10688
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10689 non-null  object
 1   Date_of_Journey  10689 non-null  object
 2   Source           10689 non-null  object
 3   Destination      10689 non-null  object
 4   Dep_Time         10689 non-null  object
 5   Arrival_Time     10689 non-null  object
 6   Duration         10689 non-null  object
 7   Total_Stops      10689 non-null  object
 8   Price            10689 non-null  float64
dtypes: float64(1), object(8)
memory usage: 751.7+ KB

## Converting categorical Columns to Numerical ones

In [17]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [18]:
df['Total_Stops'].replace({'non-stop': 0, '1 stop': 1, '2 stops': 2, '3 stops': 3, '4 stops': 4}, inplace=True)
df['Total_Stops'] = df['Total_Stops'].astype(int)

C:\Users\bhato\AppData\Local\Temp\ipykernel_21092\1733467672.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total_Stops'].replace({'non-stop': 0, '1 stop': 1, '2 stops': 2, '3 stops': 3, '4 stops': 4}, inplace=True)
C:\Users\bhato\AppData\Local\Temp\ipykernel_21092\1733467672.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Total_Stops'].replace({'non-stop': 0, '1 stop': 1, '2 stops': 2, '3 stops': 3, '4 stops': 4}, inplace=True)

In [19]:
df['Duration'].unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m'],
      dtype=object)

In [ ]:
df['Duration_Hours_Minutes'] =  0

def convert_duration_to_minutes(duration):
    hours = 0
    minutes = 0
    if 'h' in duration:
        hours = int(duration.split('h')[0])
        duration = duration.split('h')[1]
    if 'm' in duration:
        minutes = int(duration.split('m')[0])
    return (hours * 60) + minutes
df['Duration_Hours_Minutes'] = df['Duration'].apply(convert_duration_to_minutes)

In [21]:
df['Duration_Hours_Minutes'].unique()

array([ 170,  445, 1140,  325,  285,  145,  930, 1265, 1530,  470,  795,
        155,  135,  730, 1595,  270, 1355, 1380, 1235,  310,  920,  175,
        800,  910,  345,  355,  805, 1320,  330,  625,  315,  150,  375,
        715,  665,  510, 1325,  165,  720,  965, 1195,  195, 1520,  180,
        975,  905,  390, 1505,  745, 1640,  615,  630,   90,   85, 1590,
        440,  810,  300, 1145,  890,  160, 1330,  575,  600, 1280, 1125,
        740, 1080,  555, 1050,  995,  735,  450, 1440,  535,  430,  870,
       1820,  900,  765,  610,  925,  845, 1215, 1390, 1090,  960,  140,
        480, 1015,  190,  840, 1430, 1300, 1275,  650,  495,  515,  710,
       1655,  505, 1255,  290,  490, 1465, 1415, 1545, 1570, 1730, 1515,
        560,  550,  185,  690,  570, 1055,  305, 1550, 1200,  780, 1105,
       1450,  295, 1535,  380, 1120, 1165, 1760,  545,  645,  700, 1375,
       2245, 1540,  835,  520, 1410,  755, 1455,   80,  660,  675,  875,
        775,  540,  460,  705, 1495, 1025, 1795, 1335,  880,  435, 1210,
       1245, 1620, 1470, 1225,  335,  885,  340,  245,  955,  465, 1700,
        260,  220,  530, 1425, 1485, 1295,  485,  385,  950, 1585, 1490,
       1560, 1385,  475, 1580, 1395,  320,  240,  585,  500, 1045,  425,
       2045,  365,  350,  420,  265,  825, 1155, 1350,  985,  830, 1625,
       1690,  280,  940,  275, 1110, 2295,  395,  750,  680,  455, 1775,
       1615, 1420,  770,  590, 1315,  655, 1270, 1240, 1800,  790,  525,
        370, 1065, 1305,  235, 1040, 1830, 1285,  760, 1475, 1150, 1360,
        895, 1260,  405, 1720,  580, 1000,  980, 1005,   75,  415,  685,
        860,  725, 1445, 1695, 1070, 1220, 1685,  620,  855, 2115, 2135,
       1600, 1680,  865,  785, 2240, 2170, 1555, 2105, 1185, 1675, 2820,
        635,   95,  970, 2300,  360, 1010,  850, 1400, 1060,  695, 1100,
        400, 1855, 1480, 1790, 1705, 1035, 1365, 1525, 1310, 1995, 1815,
        215, 1660, 1825, 1130, 1665,  915,  640, 1575, 2185, 1610,  945,
       1180, 1345, 1175, 1500, 1605, 2280,  255, 1510, 1095,  410, 1435,
       1075, 1405, 1030, 1460, 1710, 1630, 1160,  935,  565, 1290, 2065,
       1115, 1780, 1565, 1745, 1645,  990,  670, 1735, 1750, 2040, 1840,
       1845, 1975,  605, 2120, 1925, 1900, 1190, 2025, 1810,  820, 1170,
       1890, 2070, 1670, 2315, 2525,  250, 2345,  230,    5, 1950, 1915,
       2000, 1650, 1135,  595, 2480, 1205, 1910, 2565,  205, 2230, 1770,
       1940, 1250, 2420,  815, 2860])

In [22]:
df

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Duration_Hours_Minutes
0,IndiGo,24-03-2019,Banglore,Delhi,22:20,22-03-2019 01:10,2h 50m,0,3897.0,170
1,Air India,01-05-2019,Kolkata,Banglore,05:50,13:15,7h 25m,2,7662.0,445
2,Jet Airways,09-06-2019,Delhi,Cochin,09:25,10-06-2019 04:25,19h,2,13882.0,1140
3,IndiGo,12-05-2019,Kolkata,Banglore,18:05,23:30,5h 25m,1,6218.0,325
4,IndiGo,01-03-2019,Banglore,Delhi,16:50,21:35,4h 45m,1,13302.0,285
...,...,...,...,...,...,...,...,...,...,...
10684,Air Asia,09-04-2019,Kolkata,Banglore,19:55,22:25,2h 30m,0,4107.0,150
10685,Air India,27-04-2019,Kolkata,Banglore,20:45,23:20,2h 35m,0,4145.0,155
10686,Jet Airways,27-04-2019,Banglore,Delhi,08:20,11:20,3h,0,7229.0,180
10687,Vistara,01-03-2019,Banglore,Delhi,11:30,14:10,2h 40m,0,12648.0,160
10688,Air India,09-05-2019,Delhi,Cochin,10:55,19:15,8h 20m,2,11753.0,500

### Converting Date and Time Columns to be Numerical

In [ ]:
df['Day_of_Departure'] = pd.to_datetime(df['Date_of_Journey'], format='mixed').dt.day
df['Month_of_Departure'] = pd.to_datetime(df['Date_of_Journey'],format='mixed').dt.month
df['Year_of_Departure'] = pd.to_datetime(df['Date_of_Journey'],format='mixed').dt.year
df['Dep_Time_Hour'] = pd.to_datetime(df['Dep_Time'], format='%H:%M').dt.hour
df['Dep_Time_Minute'] = pd.to_datetime(df['Dep_Time'], format='%H:%M').dt.minute

df['Arrival_Time_Hour'] = 0
df['Arrival_Time_Minute'] = 0
df['Year_of_Arrival'] = 0
df['Month_of_Arrival'] = 0
df['Day_of_Arrival'] = 0

def extract_arrival_time(row):
    arrival_time_str = row['Arrival_Time']
    if ' ' in arrival_time_str:
        date_str, time_str = arrival_time_str.split(' ')
        row['Arrival_Time_Hour'] = pd.to_datetime(time_str, format='%H:%M').hour
        row['Arrival_Time_Minute'] = pd.to_datetime(time_str, format='%H:%M').minute
        row['Year_of_Arrival'] = pd.to_datetime(date_str, format='mixed').year
        row['Month_of_Arrival'] = pd.to_datetime(date_str, format='mixed').month
        row['Day_of_Arrival'] = pd.to_datetime(date_str, format='mixed').day
    else:
        row['Arrival_Time_Hour'] = pd.to_datetime(arrival_time_str, format='%H:%M').hour
        row['Arrival_Time_Minute'] = pd.to_datetime(arrival_time_str, format='%H:%M').minute
        row['Year_of_Arrival'] = row['Year_of_Departure']
        row['Month_of_Arrival'] = row['Month_of_Departure']
        row['Day_of_Arrival'] = row['Day_of_Departure']
    return row

df = df.apply(extract_arrival_time, axis=1)

KeyError: 'Date_of_Journey'

### Dropping the columns that were transformed

In [ ]:
df.drop(['Date_of_Journey', 'Dep_Time', 'Arrival_Time', 'Duration'], axis=1, inplace=True)

,Airline,Source,Destination,Total_Stops,Price,Duration_Hours_Minutes,Day_of_Departure,Month_of_Departure,Year_of_Departure,Dep_Time_Hour,Dep_Time_Minute,Arrival_Time_Hour,Arrival_Time_Minute,Day_of_Arrival,Month_of_Arrival,Year_of_Arrival
0,IndiGo,Banglore,Delhi,0,3897.0,170,24,3,2019,22,20,1,10,22,3,2019
1,Air India,Kolkata,Banglore,2,7662.0,445,5,1,2019,5,50,13,15,5,1,2019
2,Jet Airways,Delhi,Cochin,2,13882.0,1140,6,9,2019,9,25,4,25,6,10,2019
3,IndiGo,Kolkata,Banglore,1,6218.0,325,5,12,2019,18,5,23,30,5,12,2019
4,IndiGo,Banglore,Delhi,1,13302.0,285,3,1,2019,16,50,21,35,3,1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10684,Air Asia,Kolkata,Banglore,0,4107.0,150,4,9,2019,19,55,22,25,4,9,2019
10685,Air India,Kolkata,Banglore,0,4145.0,155,27,4,2019,20,45,23,20,27,4,2019
10686,Jet Airways,Banglore,Delhi,0,7229.0,180,27,4,2019,8,20,11,20,27,4,2019
10687,Vistara,Banglore,Delhi,0,12648.0,160,3,1,2019,11,30,14,10,3,1,2019
10688,Air India,Delhi,Cochin,2,11753.0,500,5,9,2019,10,55,19,15,5,9,2019

In [ ]:
df.to_csv('G:\\Ethans\\ML\\Projects\\Final Projects\\Airline_ML\\Data\\Airline_Cleaned.csv', index=False)

## Data Stats

In [ ]:
cleaned_df = pd.read_csv('G:\\Ethans\\ML\\Projects\\Final Projects\\Airline_ML\\Data\\Airline_Cleaned.csv')

cleaned_df.describe()

,Total_Stops,Price,Duration_Hours_Minutes,Day_of_Departure,Month_of_Departure,Year_of_Departure,Dep_Time_Hour,Dep_Time_Minute,Arrival_Time_Hour,Arrival_Time_Minute,Day_of_Arrival,Month_of_Arrival,Year_of_Arrival
count,10689.000000,10689.000000,10689.000000,10689.000000,10689.000000,10689.0,10689.000000,10689.000000,10689.000000,10689.000000,10689.000000,10689.000000,10689.0
mean,0.823931,9086.154127,642.854336,12.683226,5.534662,2019.0,12.490504,24.421836,13.350360,24.688465,13.189447,5.427355,2019.0
std,0.675341,4610.851599,507.828370,8.804989,2.987427,0.0,5.748530,18.770889,6.858799,16.502706,8.824222,2.718206,0.0
min,0.000000,1759.000000,5.000000,3.000000,1.000000,2019.0,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,2019.0
25%,0.000000,5277.000000,170.000000,5.000000,3.000000,2019.0,8.000000,5.000000,8.000000,10.000000,5.000000,3.000000,2019.0
50%,1.000000,8372.000000,520.000000,6.000000,5.000000,2019.0,11.000000,25.000000,14.000000,25.000000,13.000000,5.000000,2019.0
75%,1.000000,12373.000000,930.000000,21.000000,6.000000,2019.0,18.000000,40.000000,19.000000,35.000000,21.000000,6.000000,2019.0
max,4.000000,79512.000000,2860.000000,27.000000,12.000000,2019.0,23.000000,55.000000,23.000000,55.000000,29.000000,12.000000,2019.0

In [50]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10689 entries, 0 to 10688
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline                 10689 non-null  object
 1   Source                  10689 non-null  object
 2   Destination             10689 non-null  object
 3   Total_Stops             10689 non-null  int64
 4   Price                   10689 non-null  float64
 5   Duration_Hours_Minutes  10689 non-null  int64
 6   Day_of_Departure        10689 non-null  int64
 7   Month_of_Departure      10689 non-null  int64
 8   Year_of_Departure       10689 non-null  int64
 9   Dep_Time_Hour           10689 non-null  int64
 10  Dep_Time_Minute         10689 non-null  int64
 11  Arrival_Time_Hour       10689 non-null  int64
 12  Arrival_Time_Minute     10689 non-null  int64
 13  Day_of_Arrival          10689 non-null  int64
 14  Month_of_Arrival        10689 non-null  int64
 15  Year_of_Arrival         10689 non-null  int64
dtypes: float64(1), int64(12), object(3)
memory usage: 1.3+ MB

## Saving Cleaned and Split Data

In [ ]:
X_train, X_test , y_train, y_test = train_test_split(cleaned_df.drop('Price', axis=1), cleaned_df['Price'], test_size=0.2, random_state=42)

In [3]:
X_train.to_csv('G:\\Ethans\\ML\\Projects\\Final Projects\\Airline_ML\\Data\\Cleaned_Split_Data\\X_train.csv', index=False)
X_test.to_csv('G:\\Ethans\\ML\\Projects\\Final Projects\\Airline_ML\\Data\\Cleaned_Split_Data\\X_test.csv', index=False)
y_train.to_csv('G:\\Ethans\\ML\\Projects\\Final Projects\\Airline_ML\\Data\\Cleaned_Split_Data\\y_train.csv', index=False)
y_test.to_csv('G:\\Ethans\\ML\\Projects\\Final Projects\\Airline_ML\\Data\\Cleaned_Split_Data\\y_test.csv', index=False)